name: Build APK (nassim _stati_2026)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Create Android
        run: flutter create .

      - name: Clear Gradle cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf build

      - name: Fix Kotlin version compatibility
        run: |
          sed -i "s/ext.kotlin_version = .*/ext.kotlin_version = '1.9.24'/g" android/build.gradle
          cat android/build.gradle | grep kotlin_version

      - name: Add permissions
        run: |
          FILE=android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest/a\    <uses-permission android:name="android.permission.CAMERA"/> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>' "$FILE"

      - name: Clean
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: census-apk
          path: build/app/outputs/flutter-apk/app-release.apk
